name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  combined_job:
    name: Validate terraform
    runs-on: ubuntu-latest

    steps:
      - name: checkout tf code
        uses: actions/checkout@v2

      - name: Verifies the format of terraform files
        run: |
          if terraform fmt -check .; then
              echo "All files are correctly formatted."
          else
              echo "::error::Terraform files need to be formatted."
              exit 1
          fi

      - name: initiates terraform
        run: terraform init

      - name: checks terraform syntax
        run: terraform validate
