name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  combined_job:
    name: Validate terraform
    runs-on: ubuntu-latest

    steps:
      - name: checkout tf code
        uses: actions/checkout@v2
        
      - name: checks terraform syntax
        run: terraform validate
